[package]
name = "ngn-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
ngn = { path = "../ngn" }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
